#!/usr/bin/env ruby

filename = ARGV[0]
release_tag = ARGV[1]
lines = File.readlines(filename)
front_page = File.readlines("front_page.adoc")
title = release_tag ? "#{lines.shift.chomp} #{release_tag}\n" : lines.shift

total = []
total.push title
total.push front_page
total.push lines

File.open(filename,"w") do |outfile|
  outfile.puts total.join("")
end
